---
title: "add counting windows from all stages"
author: "Pooja Bhat"
date: "July 31, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Add counting windows for each stages 

```{r cars}


#### checking custom annotations of different developmental stages :


### the stages are : 
  # 1dpf
  # 256 cell stage
  # 2 cell 
  # 2dpf
  # 4pdf
  # bud
  # dome
  # oocyte
  # sphere
  # testis

path_allStages = "/Volumes/groups/ameres/Pooja/Projects/zebrafishAnnotation/dataFromAndi/for_Pooja/2016_12_QuantSeq_Annotaton/raw_data/"
stages = c("1dpf","256cell","2cell","2dpf","4dpf","bud","dome","oocyte","sphere","testis")
completePath = paste0(path_allStages,stages,"/output/final90percent/")

##### comparing high confidence ends from the different stages

completePath_highConfidenceEnds = paste0(completePath,"allAnnotations.bed")


countingWindows = lapply(completePath_highConfidenceEnds,function(x) read.delim(x,stringsAsFactors = F,header = F))
names(countingWindows) = stages

countingWindows_allStages = do.call(rbind,countingWindows)

countingWindows_allStages$stage = row.names(countingWindows_allStages)

countingWindows_allStages$stage = gsub("\\..*","",countingWindows_allStages$stage)
rownames(countingWindows_allStages) = NULL

#### group and collapse 

library(dplyr)
countingWindows_allStages$id = paste0(countingWindows_allStages$V1,countingWindows_allStages$V2,countingWindows_allStages$V3,countingWindows_allStages$V4,countingWindows_allStages$V6)
countingWindows_allStages = countingWindows_allStages %>% group_by(id) %>%  mutate(stageCombine = paste0(stage, collapse = ";")) 

countingWindows_allStages = countingWindows_allStages[!duplicated(countingWindows_allStages[,c(1:6)]),]
#countingWindows_allStages.Granges =  makeGRangesFromDataFrame(df = countingWindows_allStages,keep.extra.columns = T,ignore.strand = F,seqnames.field = "V1",start.field = "V2",end.field = "V3",starts.in.df.are.0based = T,strand.field = "V6")

write.table(countingWindows_allStages,"/Volumes/groups/ameres/Pooja/Projects/zebrafishAnnotation/zebrafish_analysis/importantDataframes/comparingAnnotationsBetweenStages/allCountingWindows_stagesCombined.bed",sep="\t",quote = F,row.names = F)


```

```{r combineWindowsForMultimapping}


##### comparing high confidence ends from the different stages

completePath_highConfidenceEnds = paste0(completePath,"countingWindows_transcriptionalOutput.bed")

countingWindows = lapply(completePath_highConfidenceEnds,function(x) read.delim(x,stringsAsFactors = F,header = F))
names(countingWindows) = stages

countingWindows_allStages = do.call(rbind,countingWindows)

countingWindows_allStages$stage = row.names(countingWindows_allStages)

countingWindows_allStages$stage = gsub("\\..*","",countingWindows_allStages$stage)
rownames(countingWindows_allStages) = NULL
countingWindows_allStages = countingWindows_allStages[!duplicated(countingWindows_allStages[,c(1:6)]),]
library(GenomicRanges)
countingWindows_allStages.Granges =  makeGRangesFromDataFrame(df = countingWindows_allStages,keep.extra.columns = T,ignore.strand = F,seqnames.field = "V1",start.field = "V2",end.field = "V3",starts.in.df.are.0based = T,strand.field = "V6")

countingWindows_allStages.Granges.Reduce = as.data.frame(reduce(x = countingWindows_allStages.Granges))
names_create = paste0("gene",c(1:nrow(countingWindows_allStages.Granges.Reduce)))
countingWindows_allStages.Granges.Reduce_rearrange = cbind.data.frame(countingWindows_allStages.Granges.Reduce$seqnames,countingWindows_allStages.Granges.Reduce$start,countingWindows_allStages.Granges.Reduce$end,names_create,countingWindows_allStages.Granges.Reduce$width,countingWindows_allStages.Granges.Reduce$strand)
colnames(countingWindows_allStages.Granges.Reduce_rearrange) = paste0("V",c(1:ncol(countingWindows_allStages.Granges.Reduce_rearrange)))
write.table(countingWindows_allStages.Granges.Reduce_rearrange,"/Volumes/groups/ameres/Pooja/Projects/zebrafishAnnotation/zebrafish_analysis/importantDataframes/comparingAnnotationsBetweenStages/windowsForMultimapper.bed",sep="\t",row.names = F,col.names = F)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
